server:
  port: 29108
  instance:
    id: sprint-board
  servlet:
    encoding:
      enabled: true
      force: true
      charset: ${file.encoding:UTF-8} # ISO-8859-1

spring:
  application:
    name: apigen-ob-edm-test
  datasource:
    url: jdbc:mysql://localhost:3306/sprint-board?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-exclude:
  - /swagger-resources/**